###
GET http://localhost:8000/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/users/696a6d532b7e1d407a8ce5b3 HTTP/1.1
Content-Type: application/json
__________________________________________________________________

###
GET http://localhost:8000/book HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/book/696a6cde2b7e1d407a8ce5b2 HTTP/1.1
Content-Type: application/json
__________________________________________________________________

